### ISSUE TITLE
Error Testing on WIDER FACE Validation Set

### ISSUE THREAD

**Issue by galuhputraa** [peteryuX/retinaface-tf2#41]
[146 / 3226] det ./data/widerface/val\images/10--People_Marching/10_People_Marching_People_Marching_10_People_Marching_People_Marching_10_People_Marching_People_Marching_10_674.jpg
Traceback (most recent call last):
  File "test_widerface.py", line 167, in <module>
    app.run(main)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\absl\app.py", line 312, in run
    _run_main(main, args)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\absl\app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "test_widerface.py", line 93, in main
    img_height_raw, img_width_raw, _ = img_raw.shape
AttributeError: 'NoneType' object has no attribute 'shape'

![image](https://user-images.githubusercontent.com/79509420/163720165-2cf105bf-6132-4476-806e-80024098e175.png)

I have the above error on some images in the validation images section "10--People_Marching" on 8 images in that folder have no attribute shape with the error above,
update:  i just realized it is because the image name on this folder is too long  and how to fix it?

when doing the testing part I follow the sequence from the beginning

with complete data preparing section with # Online Image Loading , because I experienced an error in # Binary Image (recommend): need additional space, so the second solution is online image

then download the "Retinaface ResNet50" model and immediately do the testing on the wider face and get an error like the one above which only occurs in the "10--People_Marching"" folder is it just me or am I doing something wrong? I'm really confused

Please help me

**Comment by galuhputraa** [comment]
is there a different dataset from between dataset in this repo and the http://shuoyang1213.me/WIDERFACE/index.html??
